### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by hcadoid** [mylhyl/Android-Zxing#35]
7.0 分屏下崩溃
`java.lang.ArrayIndexOutOfBoundsException: src.length=3110400 srcPos=-20628 dst.length=829437 dstPos=0 length=933
                                                                      at java.lang.System.arraycopy(System.java:521)
                                                                      at com.google.zxing.PlanarYUVLuminanceSource.getMatrix(PlanarYUVLuminanceSource.java:101)
                                                                      at com.google.zxing.common.GlobalHistogramBinarizer.getBlackMatrix(GlobalHistogramBinarizer.java:118)
                                                                      at com.google.zxing.BinaryBitmap.getBlackMatrix(BinaryBitmap.java:85)
                                                                      at com.google.zxing.qrcode.QRCodeReader.decode(QRCodeReader.java:77)
                                                                      at com.google.zxing.MultiFormatReader.decodeInternal(MultiFormatReader.java:171)
                                                                      at com.google.zxing.MultiFormatReader.decodeWithState(MultiFormatReader.java:85)
                                                                      at com.zjcs.comm.zxing.decode.DecodeHandler.decode(DecodeHandler.java:99)
                                                                      at com.zjcs.comm.zxing.decode.DecodeHandler.handleMessage(DecodeHandler.java:62)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                      at android.os.Looper.loop(Looper.java:164)
                                                                      at com.zjcs.comm.zxing.decode.DecodeThread.run(DecodeThread.java:104)`

**Comment by mylhyl** [comment]
2.0.2
