### ISSUE TITLE
横屏、竖屏一切换就崩溃

### ISSUE THREAD

**Issue by liangfengxixi** [mylhyl/Android-Zxing#67]
错误日志：
java.lang.IllegalArgumentException: Crop rectangle does not fit within image data.
        at com.google.zxing.PlanarYUVLuminanceSource.<init>(PlanarYUVLuminanceSource.java:50)
        at com.mylhyl.zxing.scanner.camera.CameraManager.buildLuminanceSource(CameraManager.java:374)
        at com.mylhyl.zxing.scanner.decode.DecodeHandler.decode(DecodeHandler.java:95)
        at com.mylhyl.zxing.scanner.decode.DecodeHandler.handleMessage(DecodeHandler.java:62)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at com.mylhyl.zxing.scanner.decode.DecodeThread.run(DecodeThread.java:107)

**Comment by liangfengxixi** [comment]
找到原因了，我manifest设置了android:configChanges="orientation|keyboardHidden|screenSize"
横竖屏切换生命周期不会重新运行，导致onResume()里的重置没有触发，去掉这一行就可以了
